import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MarketingLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <h1>Marketing Layout</h1>
      <p>This is the layout for the marketing section.</p>
      {children}
    </div>
  );
};

export default MarketingLayout;
